### ISSUE TITLE
It isn't making any .pickle files for some reason

### ISSUE THREAD

**Issue by zombodotcom** [maximumstock/poe-currency-flip-planner#1]
```
$:~/dev/poe-currency-flip-planner$ sudo sh run_collector.sh 
Fetching Delve offers for 17 currencies - 272 pairs
^CTraceback (most recent call last):
  File "data_analysis/collector.py", line 30, in <module>
    run()
  File "data_analysis/collector.py", line 22, in run
    p.run(3)
  File "/home/$$$$/dev/poe-currency-flip-planner/src/pathfinder.py", line 57, in run
    self.offers = self.backend.fetch_offers(self.league, currency_combinations)
  File "/home/$$$$/dev/poe-currency-flip-planner/src/backends/poeofficial.py", line 15, in fetch_offers
    offers = list(map(lambda x: x, futures))
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 427, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

It isn't making any .pickle files for some reason

**Comment by maximumstock** [comment]
Hey, I think it is simply taking too long to run all 272 requests (one for each currency pair). I recently decreased the number of parallel requests to avoid being rate-limited.

Just to make sure it works, you can decrease the number of currencies the tool uses to find profitable conversions, by choosing fewer currencies here https://github.com/maximumstock/poe-currency-flip-planner/blob/master/data_analysis/collector.py#L21, for example `currencies[:8]`.

It will first download all data, construct the graph, find paths and then create a pickle file.

**Comment by zombodotcom** [comment]
Thanks yeah I got a pickle from the test runs or something but I'll check that out again. Cool program btw !
