### ISSUE TITLE
Error: Rate limited during

### ISSUE THREAD

**Issue by Atraps003** [maximumstock/poe-currency-flip-planner#144]
Getting this error

```
(poe-currency-flip-planner) root@ubuntu:~/poe-currency-flip-planner# python cli.py --league hardcore
Fetching hardcore offers for 120 pairs
Filter: Enabled
Backend: poeofficial
Rate limited during: Chaos Orb -> Ancient Orb
Rate limited during: Chaos Orb -> Aetheric Fossil
Rate limited during: Chaos Orb -> Awakened Sextant
Rate limited during: Chaos Orb -> Simple Sextant
Rate limited during: Awakened Sextant -> Chaos Orb
Rate limited during: Jeweller's Orb -> Blessed Orb
Rate limited during: Aetheric Fossil -> Chaos Orb
Rate limited during: Blessed Orb -> Chaos Orb
Rate limited during: Chromatic Orb -> Chaos Orb
Rate limited during: Divine Orb -> Chaos Orb
Rate limited during: Cartographer's Chisel -> Chaos Orb
Rate limited during: Gilded Divination Scarab -> Chaos Orb
Rate limited during: Jeweller's Orb -> Chaos Orb
Rate limited during: Gemcutter's Prism -> Chaos Orb
Rate limited during: Jagged Fossil -> Chaos Orb
Rate limited during: Orb of Alchemy -> Chaos Orb
Rate limited during: Potent Alchemical Resonator -> Chaos Orb
Rate limited during: Orb of Alteration -> Chaos Orb
Rate limited during: Potent Chaotic Resonator -> Chaos Orb
Rate limited during: Orb of Scouring -> Chaos Orb
Rate limited during: Orb of Regret -> Chaos Orb
Rate limited during: Orb of Fusing -> Chaos Orb
Rate limited during: Regal Orb -> Chaos Orb
Rate limited during: Orb of Chance -> Chaos Orb
Rate limited during: Chaos Orb -> Jagged Fossil
Rate limited during: Chaos Orb -> Orb of Annulment
Rate limited during: Chaos Orb -> Gilded Divination Scarab
Rate limited during: Vaal Orb -> Chaos Orb
Rate limited during: Shuddering Fossil -> Chaos Orb
Rate limited during: Serrated Fossil -> Chaos Orb
Rate limited during: Simple Sextant -> Chaos Orb
Rate limited during: Chaos Orb -> Encrusted Fossil
Rate limited during: Jeweller's Orb -> Cartographer's Chisel
Rate limited during: Chaos Orb -> Cartographer's Chisel
Rate limited during: Chromatic Orb -> Cartographer's Chisel
Rate limited during: Gemcutter's Prism -> Cartographer's Chisel
Rate limited during: Orb of Alchemy -> Cartographer's Chisel
Rate limited during: Orb of Alteration -> Cartographer's Chisel
Rate limited during: Orb of Regret -> Cartographer's Chisel
Rate limited during: Orb of Fusing -> Cartographer's Chisel
Rate limited during: Orb of Alchemy -> Chromatic Orb
Rate limited during: Orb of Fusing -> Chromatic Orb
Rate limited during: Chaos Orb -> Chromatic Orb
Rate limited during: Cartographer's Chisel -> Chromatic Orb
Rate limited during: Exalted Orb -> Chromatic Orb
Rate limited during: Orb of Alteration -> Chromatic Orb
Rate limited during: Orb of Chance -> Chromatic Orb
Rate limited during: Jeweller's Orb -> Chromatic Orb
Rate limited during: Cartographer's Chisel -> Exalted Orb
Rate limited during: Vaal Orb -> Chromatic Orb
Rate limited during: Regal Orb -> Chromatic Orb
Rate limited during: Chaos Orb -> Divine Orb
Rate limited during: Chaos Orb -> Exalted Orb
Rate limited during: Gemcutter's Prism -> Exalted Orb
Rate limited during: Chromatic Orb -> Exalted Orb
Rate limited during: Blessed Orb -> Exalted Orb
Rate limited during: Chaos Orb -> Regal Orb
Rate limited during: Cartographer's Chisel -> Regal Orb
Rate limited during: Orb of Annulment -> Exalted Orb
Rate limited during: Orb of Fusing -> Exalted Orb
Rate limited during: Orb of Alchemy -> Exalted Orb
Rate limited during: Chaos Orb -> Serrated Fossil
Rate limited during: Chaos Orb -> Prime Sextant
Rate limited during: Orb of Chance -> Exalted Orb
Rate limited during: Chaos Orb -> Gemcutter's Prism
Rate limited during: Orb of Scouring -> Exalted Orb
Rate limited during: Exalted Orb -> Jeweller's Orb
Rate limited during: Regal Orb -> Exalted Orb
Rate limited during: Chromatic Orb -> Jeweller's Orb
Rate limited during: Orb of Regret -> Exalted Orb
Rate limited during: Chaos Orb -> Harbinger's Orb
Rate limited during: Chaos Orb -> Jeweller's Orb
Rate limited during: Orb of Alteration -> Jeweller's Orb
Rate limited during: Cartographer's Chisel -> Orb of Alchemy
Rate limited during: Orb of Alchemy -> Jeweller's Orb
Rate limited during: Orb of Fusing -> Jeweller's Orb
Rate limited during: Chromatic Orb -> Orb of Alchemy
Rate limited during: Jeweller's Orb -> Orb of Alchemy
Rate limited during: Orb of Alteration -> Orb of Alchemy
Rate limited during: Chaos Orb -> Orb of Alchemy
Rate limited during: Orb of Transmutation -> Orb of Alchemy
Rate limited during: Orb of Chance -> Orb of Alchemy
Rate limited during: Gemcutter's Prism -> Orb of Alteration
Rate limited during: Orb of Fusing -> Orb of Alchemy
Rate limited during: Exalted Orb -> Orb of Alteration
Rate limited during: Chromatic Orb -> Orb of Alteration
Rate limited during: Chaos Orb -> Orb of Alteration
Rate limited during: Jeweller's Orb -> Orb of Alteration
Rate limited during: Orb of Transmutation -> Orb of Alteration
Rate limited during: Orb of Scouring -> Orb of Alteration
Rate limited during: Orb of Alchemy -> Orb of Alteration
Rate limited during: Orb of Alchemy -> Orb of Chance
Rate limited during: Orb of Fusing -> Orb of Alteration
Rate limited during: Chaos Orb -> Orb of Chance
Rate limited during: Orb of Scouring -> Orb of Chance
Rate limited during: Vaal Orb -> Orb of Alteration
Rate limited during: Exalted Orb -> Orb of Fusing
Rate limited during: Chaos Orb -> Orb of Fusing
Rate limited during: Chaos Orb -> Orb of Regret
Rate limited during: Vaal Orb -> Orb of Fusing
Rate limited during: Cartographer's Chisel -> Orb of Regret
Rate limited during: Vaal Orb -> Orb of Chance
Rate limited during: Chromatic Orb -> Orb of Fusing
Rate limited during: Orb of Alteration -> Orb of Fusing
Rate limited during: Orb of Alteration -> Orb of Scouring
Rate limited during: Orb of Fusing -> Orb of Scouring
Rate limited during: Orb of Regret -> Orb of Scouring
Rate limited during: Orb of Alteration -> Orb of Regret
Rate limited during: Chaos Orb -> Orb of Transmutation
Rate limited during: Chaos Orb -> Potent Chaotic Resonator
Rate limited during: Chaos Orb -> Orb of Scouring
Rate limited during: Chaos Orb -> Potent Alchemical Resonator
Rate limited during: Chaos Orb -> Shuddering Fossil
Rate limited during: Cartographer's Chisel -> Vaal Orb
Rate limited during: Orb of Alteration -> Regal Orb
Rate limited during: Orb of Alchemy -> Vaal Orb
Rate limited during: Chaos Orb -> Vaal Orb
Rate limited during: Exalted Orb -> Vaal Orb
Rate limited during: Orb of Alteration -> Vaal Orb
Rate limited during: Orb of Fusing -> Vaal Orb
Failed to fetch offers for 120 pairs
Traceback (most recent call last):
  File "cli.py", line 114, in <module>
    p.run(3)
  File "/root/poe-currency-flip-planner/src/pathfinder.py", line 143, in run
    self._fetch()
  File "/root/poe-currency-flip-planner/src/pathfinder.py", line 97, in _fetch
    self.offers = self._filter_traders(self.offers, self.excluded_traders)
  File "/root/poe-currency-flip-planner/src/pathfinder.py", line 75, in _filter_traders
    offers[idx]["offers"],
TypeError: 'NoneType' object is not subscriptable
(poe-currency-flip-planner) root@ubuntu:~/poe-currency-flip-planner#

```

**Comment by maximumstock** [comment]
I'm looking into this already, but it seems the rate-limit of the official trade API has changed in a way which makes this workflow impossible unless one wants to wait 90+ seconds.

For now you can pass the `--poetrade` flag to switch to poe.trade as a backend. This speeds up the process alot.

**Comment by Atraps003** [comment]
Thanks for the information. I confirm --poetrade works.

**Comment by maximumstock** [comment]
I'll close this for now as the latest changes should fix this :)
 https://github.com/maximumstock/poe-currency-flip-planner/releases/tag/0.3.0
