### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by HiPoEGH** [maximumstock/poe-currency-flip-planner#146]
Currently getting errors for running on either poetrade or poeofficial.

> Fetching Delirium offers for 114 pairs
Filter: Enabled
Backend: poetrade
Spent 43.64s fetching offers
Spent 0.0s building the graph
Checking for profitable conversions...
Traceback (most recent call last):
  File "D:/bt  stuff/poe-currency-flip-planner-master (3)/poe-currency-flip-planner-master/cli.py", line 114, in <module>
    p.run(2)
  File "D:\bt  stuff\poe-currency-flip-planner-master (3)\poe-currency-flip-planner-master\src\pathfinder.py", line 147, in run
    self._find_profitable_paths(max_transaction_length)
  File "D:\bt  stuff\poe-currency-flip-planner-master (3)\poe-currency-flip-planner-master\src\pathfinder.py", line 120, in _find_profitable_paths
    paths = graph.find_paths(self.graph, c, c, self.user_config, max_transaction_length)
  File "D:\bt  stuff\poe-currency-flip-planner-master (3)\poe-currency-flip-planner-master\src\core\graph.py", line 53, in find_paths
    if edge["stock"] < minimum or edge["stock"] > maximum:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
Process finished with exit code 1

**Comment by maximumstock** [comment]
Seems like you either have an error in your custom stock configuration or my code does not handle some edge case.

Can you check your configuration whether one of your `maximum_stock` values contains a non-numeric value? In case you are fine with posting your configuration or via mail, I can take a further look myself.

**Comment by HiPoEGH** [comment]
I used the default configuration and it works.
I must have done something odd. Maybe a missing pair or wrong maximum stock, idk. I tried removing some items I did not want to pair with others.
