### ISSUE TITLE
requirements.txt update - add deserialize

### ISSUE THREAD

**Issue by iMartyn** [maximumstock/poe-currency-flip-planner#246]
Clean python install doesn't necessarily have deserialize :

On a clean python 3.7 on debian buster, for instance with this Dockerfile :
```
FROM python:3.7-buster
RUN git clone https://github.com/maximumstock/poe-currency-flip-planner.git
RUN cd poe-currency-flip-planner ; pip install -r requirements.txt
```

You still have to `pip install deserialize` :

```
root@174e58b83184:/poe-currency-flip-planner# python cli.py --league "Harvest"
Traceback (most recent call last):
  File "cli.py", line 5, in <module>
    from src.config.user_config import UserConfig
  File "/poe-currency-flip-planner/src/config/user_config.py", line 8, in <module>
    from src.trading import StackSizeHelper
  File "/poe-currency-flip-planner/src/trading/__init__.py", line 1, in <module>
    from .items import Item, ItemList, UnknownBackendException, UnsupportedItemException
  File "/poe-currency-flip-planner/src/trading/items.py", line 24, in <module>
    import deserialize
ModuleNotFoundError: No module named 'deserialize'
root@174e58b83184:/poe-currency-flip-planner# pip install deserialize
Collecting deserialize
  Downloading deserialize-1.8.0-py3-none-any.whl (15 kB)
Installing collected packages: deserialize
Successfully installed deserialize-1.8.0
root@174e58b83184:/poe-currency-flip-planner# python cli.py --league "Harvest"
Fetching Harvest offers for 120 pairs
```

**Comment by maximumstock** [comment]
Should be fixed via https://github.com/maximumstock/poe-currency-flip-planner/commit/2eea1e67e51612e0e929d5bed3efefba7f7c689a as well.

**Comment by iMartyn** [comment]
Confirmed working here.
